org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Maven coordinates (override VERSION for releases)
GROUP=io.github.prowllabs
VERSION=1.0.0
POM_URL=https://github.com/ProwlLabs/prowlkit-android
POM_SCM_URL=https://github.com/ProwlLabs/prowlkit-android
POM_SCM_CONNECTION=scm:git:git://github.com/ProwlLabs/prowlkit-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ProwlLabs/prowlkit-android.git
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=prowllabs
POM_DEVELOPER_NAME=ProwlLabs
